name: jimpact
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  flutter_riverpod: ^2.3.6
  fpdart: ^0.3.0
  shared_preferences: ^2.0.15
  http: ^1.0.0
  flutter_animate: ^1.0.0
  flutter_svg: ^2.0.2
  routemaster: ^1.0.1
  uuid: ^3.0.6
  phosphor_flutter: ^1.4.0
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  url_launcher: ^6.1.10
  loading_animation_widget: ^1.2.0+3
  smooth_page_indicator: ^1.1.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.5
  dotted_line: ^3.1.0
  cached_network_image: ^3.2.3
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^4.2.1
  pinput: ^2.2.31
  image_picker: ^0.8.7+5
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image: ^4.0.17
  mime_type: ^1.0.0
  http_parser: ^4.0.2
  substring_highlight: ^1.0.33
  local_hero: ^0.2.0
  dropdown_button2: ^1.9.2
  skeletonizer: ^0.8.0
  camera: ^0.10.5+2
  flutter_image_compress: ^2.0.3
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  simple_animations: ^5.0.0+3
  build_runner: ^2.3.2
  riverpod_lint: ^1.0.1
  custom_lint:
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
